# Site
name: "tap"
title: "TAP !"
description: "In a perfect world, the word perfect doesn't exist!"
logo: 'assets/images/favicon.svg'
favicon: 'assets/images/favicon.svg'
baseurl: ''
google_analytics: 'G-QHF2SGC76S'
analytics : "enabled"
matomo: "disabled"
matomo_site: "https://motodb.eu.org/"
matomo_id: "2"
disqus: 'tapsaja'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
mailchimp-list: '/form'
contact-form: 'https://formspree.io/f/xrbggvqa'
include: ["_pages"]
permalink: /:year:month/:title/
email: tap@e.email
localcss: "true"

# Authors
authors:
  tap:
    name: tap
    display_name: tap
    avatar: 'assets/images/tap.webp'
    email: '/contact'
    web: https://tapsaja.github.io
    twitter: https://twitter.com/tap_saja
    description: "Just tap it, will ya"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# SEO
seo:
  generator: false

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
